name: Build cryptad snap (amd64/arm64)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g. 1.2.3). If set, checks out release/<version>"
        required: false
        default: ""
      branch:
        description: "Branch or tag to build when version is empty"
        required: false
        default: "main"
  workflow_call:
    inputs:
      version:
        description: "Version number (e.g. 1.2.3). If set, checks out release/<version>"
        required: false
        type: string
        default: ""
      branch:
        description: "Branch or tag to build when version is empty"
        required: false
        type: string
        default: "main"
    outputs:
      version:
        description: "Resolved version used for this build"
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    outputs:
      version: ${{ steps.prepare.outputs.version }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout release-ops repo
        uses: actions/checkout@v4

      - name: Prepare upstream (version + dist tarball)
        id: prepare
        uses: ./.github/actions/prepare-cryptad
        with:
          version: ${{ inputs.version }}
          branch: ${{ inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare snap payload (repack)
        id: repack
        uses: ./.github/actions/repack-payload
        with:
          tarball_path: ${{ steps.prepare.outputs.tarball_path }}
          version: ${{ steps.prepare.outputs.version }}
          output_dir: snap/local

      - name: Prepare desktop assets (icon)
        run: |
          set -euo pipefail
          echo "::group::Prepare desktop icon"
          mkdir -p snap/gui
          if [ -f desktop/icons/cryptad.png ]; then
            cp -f desktop/icons/cryptad.png snap/gui/cryptad.png
            (ls -la snap/gui | sed 's/^/::debug::[snap-gui] /')
          else
            echo "::warning::desktop/icons/cryptad.png not found; desktop icon will be missing"
          fi
          echo "::endgroup::"

      - name: Render desktop file from shared template
        uses: ./.github/actions/render-desktop
        with:
          template_path: desktop/cryptad.desktop.template
          exec_name: cryptad.cryptad-launcher
          icon_name: ${SNAP}/meta/gui/cryptad.png
          output_path: snap/gui/cryptad.desktop

      - name: List snap dir (pre-pack)
        run: |
          echo "::group::List snap tree before snapcraft"
          find snap -maxdepth 3 -printf '%M %u %g %9s %TY-%Tm-%Td %TH:%TM %p\n' 2>/dev/null | sed 's/^/::debug::[snap-pre] /' || true
          echo "::debug::Show rendered desktop head"
          sed -n '1,80p' snap/gui/cryptad.desktop | sed 's/^/::debug::[desktop] /' || true
          echo "::endgroup::"

      - name: Generate snapcraft.yaml from template
        uses: ./.github/actions/render-manifest
        with:
          template_path: snap/snapcraft.yaml.template
          output_path: snap/snapcraft.yaml
          substitutions: |
            __VERSION__=${{ steps.prepare.outputs.version }}
          preview_lines: "160"

      - name: Environment diag (arch + kernel)
        run: |
          echo "::debug::Host arch: $(dpkg --print-architecture || true)"
          echo "::debug::Kernel: $(uname -a)"

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v3

      - name: Build snap (native arch, no LXD)
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT: host
        run: |
          echo "::group::snapcraft ${{ matrix.arch }} (pack on host)"
          sudo -E snapcraft pack --platform ${{ matrix.arch }} --verbosity=debug
          echo "::endgroup::"

      - name: Debug: list snapcraft work dirs (always)
        if: always()
        run: |
          echo "::group::List Snapcraft work dirs (parts/, prime/, stage/)"
          for d in parts prime stage; do
            if [ -d "$d" ]; then
              echo "::debug::[$d]"; find "$d" -maxdepth 3 -type f -printf '%M %u %g %9s %TY-%Tm-%Td %TH:%TM %p\n' | sed "s#^#::debug::[$d] #" || true;
            else
              echo "::debug::missing $d";
            fi
          done
          if [ -d prime/meta/gui ]; then
            echo "::debug::[prime/meta/gui] contents:"; ls -la prime/meta/gui | sed 's/^/::debug::[prime-gui] /' || true
            for f in prime/meta/gui/*.desktop; do
              [ -e "$f" ] || continue; echo "::debug::[head] $f"; sed -n '1,80p' "$f" | sed 's/^/::debug::[head] /'; done
          fi
          echo "::endgroup::"

      - name: List built snaps
        run: |
          echo "::group::List .snap files in workspace"
          find . -maxdepth 2 -type f -name '*.snap' -print | sed 's/^/::debug::[snap] /' || true
          echo "::endgroup::"

      - name: Normalize snap filename (cryptad-v<version>-<arch>.snap)
        shell: bash
        run: |
          set -euo pipefail
          VERSION='${{ steps.prepare.outputs.version }}'
          ARCH='${{ matrix.arch }}'
          mkdir -p artifacts-snap
          SNAP_FILE=$(find . -maxdepth 2 -type f -name "*.snap" -print0 | xargs -0 ls -1t 2>/dev/null | head -n1 || true)
          if [ -z "$SNAP_FILE" ]; then
            echo "::error::No .snap produced"
            exit 1
          fi
          OUT="artifacts-snap/cryptad-v${VERSION}-${ARCH}.snap"
          mv "$SNAP_FILE" "$OUT"
          echo "::debug::Renamed $SNAP_FILE -> $OUT"

      - name: Upload amd64 snap
        if: matrix.arch == 'amd64'
        uses: actions/upload-artifact@v4
        with:
          name: cryptad-snap-${{ steps.prepare.outputs.version }}-amd64
          path: artifacts-snap/cryptad-v${{ steps.prepare.outputs.version }}-amd64.snap
          if-no-files-found: error

      - name: Upload arm64 snap
        if: matrix.arch == 'arm64'
        uses: actions/upload-artifact@v4
        with:
          name: cryptad-snap-${{ steps.prepare.outputs.version }}-arm64
          path: artifacts-snap/cryptad-v${{ steps.prepare.outputs.version }}-arm64.snap
          if-no-files-found: error
