name: Build cryptad snap (amd64/arm64)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g. 1.2.3). If set, checks out release/<version>"
        required: false
        default: ""
      branch:
        description: "Branch or tag to build when version is empty"
        required: false
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout release-ops repo
        uses: actions/checkout@v4

      - name: Decide upstream ref
        id: ref
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            echo "ref=release/${{ inputs.version }}" >> "$GITHUB_OUTPUT"
          else
            echo "ref=${{ inputs.branch }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout upstream cryptad (${{ steps.ref.outputs.ref }})
        uses: actions/checkout@v4
        with:
          repository: crypta-network/cryptad
          ref: ${{ steps.ref.outputs.ref }}
          path: upstream

      - name: Set up JDK 21 (temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Determine version via gradle printVersion or fallback
        id: ver
        working-directory: upstream
        run: |
          set -euo pipefail
          VERSION_INPUT="${{ inputs.version }}"
          VERSION=""
          # Prefer the Nebula Release task if available
          if ./gradlew -q tasks --all | grep -q "^printVersion"; then
            VERSION=$(./gradlew -q printVersion | tail -n1 | tr -d '[:space:]')
          fi
          if [ -z "$VERSION" ]; then
            # Try gradle.properties: version=...
            if [ -f gradle.properties ]; then
              VERSION=$(grep -E '^[[:space:]]*version[[:space:]]*[:=][[:space:]]*' gradle.properties | tail -n1 | sed -E 's/^[^:=]+[:=][[:space:]]*//' | tr -d '[:space:]' | tr -d '"' | tr -d "'")
            fi
          fi
          if [ -z "$VERSION" ]; then
            # Last resort: use git describe (strip leading 'v')
            VERSION=$(git describe --tags --always --abbrev=0 2>/dev/null | sed 's/^v//') || true
          fi
          if [ -z "$VERSION" ]; then
            echo "Unable to determine version" >&2
            exit 1
          fi
          echo "version=$VERSION" | tee -a "$GITHUB_OUTPUT"

      - name: Build upstream project (dist)
        id: build
        working-directory: upstream
        run: |
          set -euo pipefail
          # Build (skip tests for speed/CI stability)
          ./gradlew -S -x test build || ./gradlew -S build
          # Expected tarball path
          VERSION="${{ steps.ver.outputs.version }}"
          TARBALL="build/distributions/cryptad-v${VERSION}.tar.gz"
          if [ ! -f "$TARBALL" ]; then
            # Fallback: find any cryptad*.tar.gz built artifact
            TARBALL=$(find build -type f -name 'cryptad-*.tar.gz' | head -n1 || true)
          fi
          if [ -z "$TARBALL" ] || [ ! -f "$TARBALL" ]; then
            echo "No distribution tarball found under build/." >&2
            find build -maxdepth 3 -type f -print || true
            exit 1
          fi
          echo "$TARBALL" > "$GITHUB_WORKSPACE/.tarball-path"

      - name: Prepare snap payload (slim per-arch)
        run: |
          set -euo pipefail
          mkdir -p snap/local
          TARBALL=$(cat .tarball-path)
          VERSION='${{ steps.ver.outputs.version }}'
          WORK=workpkg
          rm -rf "$WORK"
          mkdir -p "$WORK"
          # Extract tarball contents (expecting top-level bin/, conf/, lib/)
          tar -xzf "$TARBALL" -C "$WORK"
          # Remove macOS binaries to reduce size
          rm -f "$WORK"/bin/wrapper-macosx-* "$WORK"/lib/libwrapper-macosx-* || true
          # Remove the other Linux arch to reduce size further
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            rm -f "$WORK"/bin/wrapper-linux-arm-64 "$WORK"/lib/libwrapper-linux-arm-64.so || true
          else
            rm -f "$WORK"/bin/wrapper-linux-x86-64 "$WORK"/lib/libwrapper-linux-x86-64.so || true
          fi
          tar -C "$WORK" -czf "snap/local/cryptad-v${VERSION}.tar.gz" ./

      - name: Generate snapcraft.yaml from template
        run: |
          set -euo pipefail
          VERSION='${{ steps.ver.outputs.version }}'
          sed "s/__VERSION__/${VERSION}/g" snap/snapcraft.yaml.template > snap/snapcraft.yaml
          echo "Generated snap/snapcraft.yaml:" && sed -n '1,120p' snap/snapcraft.yaml

      - name: Build snap (for ${{ matrix.arch }})
        id: snapcraft
        uses: snapcore/action-build@v1
        with:
          path: .
          # Try to build for the target architecture
          snapcraft-args: --build-for=${{ matrix.arch }}

      - name: Upload built snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: cryptad-snap-${{ steps.ver.outputs.version }}-${{ matrix.arch }}
          path: ${{ steps.snapcraft.outputs.snap }}
